# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test2
  pod 'GoogleAPIClientForREST/Sheets', '~> 1.2.1'
  pod 'GoogleSignIn', '~> 4.1.1'

  target 'test2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'test2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
